### ISSUE TITLE
Inefficiencies

### ISSUE THREAD

**Issue by ericlau00** [SolonEDU/solon-mobile#50]
- [x] Admin/Parent dart files should not be held in different folders; combine two into one and use if statements instead. 
- [x] Figure out a way to deal with lang directory; we should not need to hardcode every translation by hand if they are static. Have a machine do it!

**Comment by raymondlee00** [comment]
also converting some futurebuilders to streambuilders

**Comment by raymondlee00** [comment]
we already have a way to generate translations for static text fields, using a node package to generate localization JSONs whose file names are ISO 639-1 compliant
